sudo: required

language: node_js
node_js:
  - "8"
cache:
  directories:
    - "node_modules"

branches:
  only:
  - master

jobs:
  include:
    - stage: lint
      script: npm run lint
#    - stage: test
#      script: npm run test
    - stage: build
      env: PLATFORM=armhf HASSIO=true
      services:
        - docker
      addons:
        apt:
          packages:
            - docker-ce
      script: ./build-docker.sh
    - env: PLATFORM=aarch64 HASSIO=true
      services:
        - docker
      addons:
        apt:
          packages:
            - docker-ce
      script: ./build-docker.sh
    - env: PLATFORM=amd64 HASSIO=true
      services:
        - docker
      addons:
        apt:
          packages:
            - docker-ce
      script: ./build-docker.sh
    - env: PLATFORM=i386 HASSIO=true
      services:
        - docker
      addons:
        apt:
          packages:
            - docker-ce
      script: ./build-docker.sh
    - env: PLATFORM=amd64
      services:
        - docker
      addons:
        apt:
          packages:
            - docker-ce
      script: ./build-docker.sh
    - env: PLATFORM=arm32
      services:
        - docker
      addons:
        apt:
          packages:
            - docker-ce
      before_script:
        - wget https://github.com/multiarch/qemu-user-static/releases/download/v2.12.0/qemu-arm-static.tar.gz -O /tmp/qemu-arm-static.tar.gz
        - tar zxvf /tmp/qemu-arm-static.tar.gz -C .
        - docker run --rm --privileged multiarch/qemu-user-static:register
      script: ./build-docker.sh
